### ISSUE TITLE
关于il2CPP包的疑惑

### ISSUE THREAD

**Issue by Ferrarie** [DrFlower/Unity-Obfuscator#2]
Unity-Obfuscator对c#代码的混淆时机是否在 il to Cpp阶段之前？简单来说是否支持安卓平台的IL2CPP打包模式？

**Comment by DrFlower** [comment]
混淆时机是发生在IL2CPP之前的，已在项目实测过IOS的IL2CPP模式，没有问题，安卓应该也是一样的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DrFlower/Unity-Obfuscator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 中午1:17
收件人:&nbsp;"DrFlower/Unity-Obfuscator"<Unity-Obfuscator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[DrFlower/Unity-Obfuscator] 关于il2CPP包的疑惑 (#2)





 
Unity-Obfuscator对c#代码的混淆时机是否在 il to Cpp阶段之前？简单来说是否支持安卓平台的IL2CPP打包模式？

**Comment by Ferrarie** [comment]
多谢
